### ISSUE TITLE
couldn't find file 'jquery-tmpl' with type 'application/javascript'

### ISSUE THREAD

**Issue by wdiechmann** [jimmycuadra/jquery-tmpl-rails#9]
I'm running

Rails 4.2.1
rake, version 10.4.2
Bundler version 1.10.5
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin14.0]

and I've added

```
//= require jquery-tmpl
//= require_tree ./templates
```

to my Gem (and the jquery-tmpl-rails gem to my Gemfile of cause) - but when I use the gem the page load stops with the above mentioned "couldn't find file" error - and a stack trace looking like this:

```
/Users/walther/Projects/gems/oxen_media/app/assets/javascripts/oxen_media.js:2
sprockets (3.2.0) lib/sprockets/resolve.rb:64:in `resolve!'
sprockets (3.2.0) lib/sprockets/directive_processor.rb:399:in `resolve'
sprockets (3.2.0) lib/sprockets/directive_processor.rb:207:in `process_require_directive'
sprockets (3.2.0) lib/sprockets/directive_processor.rb:180:in `block in process_directives'
sprockets (3.2.0) lib/sprockets/directive_processor.rb:178:in `each'
sprockets (3.2.0) lib/sprockets/directive_processor.rb:178:in `process_directives'
sprockets (3.2.0) lib/sprockets/directive_processor.rb:83:in `_call'
sprockets (3.2.0) lib/sprockets/directive_processor.rb:68:in `call'
sprockets (3.2.0) lib/sprockets/processor_utils.rb:75:in `call_processor'
sprockets (3.2.0) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
sprockets (3.2.0) lib/sprockets/processor_utils.rb:56:in `reverse_each'
sprockets (3.2.0) lib/sprockets/processor_utils.rb:56:in `call_processors'
sprockets (3.2.0) lib/sprockets/loader.rb:86:in `load_asset_by_uri'
sprockets (3.2.0) lib/sprockets/loader.rb:45:in `block in load'
sprockets (3.2.0) lib/sprockets/loader.rb:155:in `fetch_asset_from_dependency_cache'
sprockets (3.2.0) lib/sprockets/loader.rb:38:in `load'
sprockets (3.2.0) lib/sprockets/cached_environment.rb:20:in `block in initialize'
sprockets (3.2.0) lib/sprockets/cached_environment.rb:47:in `yield'
sprockets (3.2.0) lib/sprockets/cached_environment.rb:47:in `load'
sprockets (3.2.0) lib/sprockets/bundle.rb:23:in `block in call'
sprockets (3.2.0) lib/sprockets/utils.rb:183:in `dfs'
sprockets (3.2.0) lib/sprockets/bundle.rb:24:in `call'
sprockets (3.2.0) lib/sprockets/processor_utils.rb:75:in `call_processor'
sprockets (3.2.0) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
sprockets (3.2.0) lib/sprockets/processor_utils.rb:56:in `reverse_each'
sprockets (3.2.0) lib/sprockets/processor_utils.rb:56:in `call_processors'
sprockets (3.2.0) lib/sprockets/loader.rb:86:in `load_asset_by_uri'
sprockets (3.2.0) lib/sprockets/loader.rb:45:in `block in load'
sprockets (3.2.0) lib/sprockets/loader.rb:155:in `fetch_asset_from_dependency_cache'
sprockets (3.2.0) lib/sprockets/loader.rb:38:in `load'
sprockets (3.2.0) lib/sprockets/cached_environment.rb:20:in `block in initialize'
sprockets (3.2.0) lib/sprockets/cached_environment.rb:47:in `yield'
sprockets (3.2.0) lib/sprockets/cached_environment.rb:47:in `load'
sprockets (3.2.0) lib/sprockets/base.rb:63:in `find_asset'
sprockets (3.2.0) lib/sprockets/environment.rb:30:in `find_asset'
sprockets (3.2.0) lib/sprockets/base.rb:89:in `[]'
sprockets-rails (2.3.2) lib/sprockets/rails/helper.rb:230:in `lookup_asset_for_path'
sprockets-rails (2.3.2) lib/sprockets/rails/helper.rb:190:in `check_errors_for'
sprockets-rails (2.3.2) lib/sprockets/rails/helper.rb:137:in `block in javascript_include_tag'
sprockets-rails (2.3.2) lib/sprockets/rails/helper.rb:136:in `map'
sprockets-rails (2.3.2) lib/sprockets/rails/helper.rb:136:in `javascript_include_tag'
app/views/layouts/_head.html.haml:26:in `_app_views_layouts__head_html_haml___3569935750097020933_70308056945640'

```

might you have a clou on this?

cheers,
Walther

**Comment by cdale77** [comment]
Just ran into this. I'm pretty sure it's due to a change in how Sprockets handles registering mime type handlers. The PR https://github.com/jimmycuadra/jquery-tmpl-rails/pull/10 looks promising, but it doesn't work for me, possibly because the templates (I inherited) are written in haml.
